In [1]:
import mxnet as mx
from mxnet import nd

In [3]:
sample_array = nd.arange(12)

In [4]:
sample_array


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [5]:
shape = sample_array.shape
shape

(12,)

In [6]:
size = sample_array.size
size

12

In [7]:
reshaped_array = sample_array.reshape(3, 4)
reshaped_array


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
reshape_to_zeroes = nd.zeros((2, 3, 4))
reshape_to_zeroes


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [13]:
reshape_to_ones = nd.ones((2, 3, 4))
reshape_to_ones


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [15]:
tensor_matrix = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tensor_matrix


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>