<a href="https://colab.research.google.com/github/purvasingh96/pytorch-examples/blob/master/Basics/01.%20Deep_Learning_with_PyTorch_A_60_Minute_Blitz_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is PyTorch?
A scientific computing package that is -
* A replacement for NumPy to use the power of GPUs
* A deep learning research platform that provides maximum flexibility and speed
# Getting Started 
### Tensors

* Empty tensor gets initialized with random values allocated at run time.

In [0]:
from __future__ import print_function
import torch 

In [9]:
empty_tensor = torch.empty(5, 3)
zero_tensor = torch.zeros(5, 3, dtype=torch.long)
direct_tensor = torch.tensor([5, 5, 6, 8])
one_tensor = zero_tensor.new_ones(5, 3, dtype=torch.double)

print('Empty Tensor : \n', empty_tensor)
print('\n')
print('Zero Tensor : \n', zero_tensor)
print('\n')
print('Direct Tensor : \n', direct_tensor)
print('\n')
print('Ones Tensor : \n', one_tensor)

Empty Tensor : 
 tensor([[5.7450e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 1.6255e-43],
        [2.6194e+20, 1.6427e-07, 1.6595e-07],
        [2.1781e-04, 4.1723e-08, 6.7130e-07],
        [3.3090e+21, 3.4003e-06, 0.0000e+00]])


Zero Tensor : 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Direct Tensor : 
 tensor([5, 5, 6, 8])


Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
old_tensor = one_tensor
new_tensor = torch.rand_like(old_tensor, dtype=torch.float)

print('Size of new tensor : ', new_tensor.size())
print('\n')
print('Old tensor with overridden dType and same size as old_tensor : \n',new_tensor)

Size of new tensor :  torch.Size([5, 3])


Old tensor with overridden dType and same size as old_tensor : 
 tensor([[0.5932, 0.1361, 0.9276],
        [0.4668, 0.4190, 0.5359],
        [0.6300, 0.0740, 0.5790],
        [0.6140, 0.6834, 0.3323],
        [0.5462, 0.8163, 0.9566]])


### Operations


In [16]:
new_tensor = torch.rand(5, 3)
simple_addition = old_tensor + new_tensor
torch_add = torch.add(old_tensor, new_tensor)
output_tensor_as_argument = torch.empty(5, 3)
torch.add(old_tensor, new_tensor, out=output_tensor_as_argument)
inplace_addition = new_tensor.add_(old_tensor)

print('x + y : \n', simple_addition)
print('\n')
print('torch.add() : \n', torch_add)
print('\n')
print('Output tensor as argument : \n', output_tensor_as_argument)
print('\n')
print('In-place addition : \n', inplace_addition)

x + y : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]], dtype=torch.float64)


torch.add() : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]], dtype=torch.float64)


Output tensor as argument : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]])


In-place addition : 
 tensor([[1.9855, 1.2796, 1.9305],
        [1.9259, 1.3387, 1.6248],
        [1.9437, 1.8683, 1.1107],
        [1.2303, 1.0151, 1.3394],
        [1.0631, 1.6831, 1.7090]])


### Indexing Tensors


In [17]:
print('Print first row : \n', new_tensor[:, 1])

Print first row : 
 tensor([1.2796, 1.3387, 1.8683, 1.0151, 1.6831])


In [21]:
four_by_four_tensor = torch.rand(4, 4)
resized_tensor = four_by_four_tensor.view(16)
new_resized_tensor = resized_tensor.view(-1, 8)
one_element = torch.rand(1)
indexing_one_element = one_element.item() 

print('four_by_four_tensor : \n', four_by_four_tensor, four_by_four_tensor.size())
print('\nresized_tensor : ', resized_tensor, resized_tensor.size())
print('\nnew resized_tensor : ', new_resized_tensor, new_resized_tensor.size())
print('\n Indexing tensor with one element only : ', one_element)

four_by_four_tensor : 
 tensor([[0.0967, 0.3639, 0.2226, 0.1716],
        [0.5799, 0.6646, 0.5323, 0.0392],
        [0.9341, 0.1982, 0.9859, 0.1644],
        [0.1394, 0.9150, 0.9714, 0.4409]]) torch.Size([4, 4])

resized_tensor :  tensor([0.0967, 0.3639, 0.2226, 0.1716, 0.5799, 0.6646, 0.5323, 0.0392, 0.9341,
        0.1982, 0.9859, 0.1644, 0.1394, 0.9150, 0.9714, 0.4409]) torch.Size([16])

new resized_tensor :  tensor([[0.0967, 0.3639, 0.2226, 0.1716, 0.5799, 0.6646, 0.5323, 0.0392],
        [0.9341, 0.1982, 0.9859, 0.1644, 0.1394, 0.9150, 0.9714, 0.4409]]) torch.Size([2, 8])

 Indexing tensor with one element only :  tensor([0.5945])


### NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa.

In [25]:
import numpy as np

torch_array = torch.rand(5)
print('Original torch array : \n', torch_array)

torch_to_numpy = torch_array.numpy()
print('\nTorch array converted to numpy : \n', torch_to_numpy)

numpy_array = np.ones(5)
print('\nOriginal numpy array : \n', numpy_array)

numpy_to_torch = torch.from_numpy(numpy_array)
print('\nNumpy array converted to torch : \n', numpy_to_torch)




Original torch array : 
 tensor([0.3167, 0.3007, 0.1896, 0.0640, 0.8503])

Torch array converted to numpy : 
 [0.31668967 0.30073845 0.18957937 0.06404227 0.85028934]

Original numpy array : 
 [1. 1. 1. 1. 1.]

Numpy array converted to torch : 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the `.to` method.

In [5]:
import torch

if torch.cuda.is_available:
  device = torch.device("cuda")
  new_tensor = torch.rand(1)
  cuda_tensor = torch.ones_like(new_tensor, device=device)
  non_cuda_tensor = new_tensor.to(device)
  cuda_result = cuda_tensor + non_cuda_tensor
  print('CUDA result : \n', cuda_result)
  cpu_result = cuda_result.to("cpu", torch.double)
  print('\n CPU result : \n', cpu_result)

CUDA result : 
 tensor([1.8087], device='cuda:0')

 CPU result : 
 tensor([1.8087], dtype=torch.float64)
