In [16]:
from torchvision import datasets, transforms
import torch


In [17]:
# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])

# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

In [18]:
data_iter = iter(trainloader)
images, labels = data_iter.next()
print(type(images))
print(images.shape)
print(labels.shape)

<class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64])


In [33]:
def activation(x):
    return 1/(1+torch.exp(-x))

# can replace -1 with 784
# -1 is shorter way to figure out no. of elements
inputs = images.view(images.shape[0], -1)
w1 = torch.randn(784, 256)
b1 = torch.randn(256)

w2 = torch.randn(256, 10)
b2 = torch.randn(10)

h = activation(torch.mm(inputs, w1)+b1)
output = torch.mm(h, w2)+b2

def softmax(x):
    return torch.exp(x)/(torch.sum(torch.exp(output), dim=1).view(-1, 1))

probabilities = softmax(output)
print('torch.exp(output)')
print(torch.exp(output))





torch.exp(output)
tensor([[9.3928e+02, 5.1529e+01, 3.3914e+01, 5.8258e+02, 6.4712e+06, 2.8441e+04,
         2.2175e+07, 6.2317e+04, 1.3152e-05, 3.6317e-03],
        [1.4564e+04, 1.9639e-01, 1.3018e-01, 1.2907e+00, 4.4863e+09, 8.6159e+00,
         1.4013e+03, 3.1053e+00, 1.8889e-03, 1.3143e-01],
        [2.1515e+04, 2.3775e-02, 5.5080e+05, 2.4624e+02, 2.2387e+09, 7.2506e+06,
         5.4777e+03, 2.5334e+02, 1.0506e+02, 4.1362e-02],
        [2.3888e+04, 1.1551e-02, 1.0602e+01, 7.6697e+02, 4.0714e+10, 4.3060e+06,
         1.5384e+05, 3.1277e+02, 3.2930e+01, 3.6145e+01],
        [5.2529e+03, 1.8453e+02, 4.8281e+01, 5.6539e+02, 2.5897e+02, 1.3463e+05,
         6.1113e+03, 3.5655e+06, 5.4397e-04, 7.1111e-03],
        [1.2454e+04, 3.3149e-03, 6.9184e+04, 1.4927e+02, 3.4982e+08, 5.6164e+05,
         1.1201e+01, 3.2294e+04, 2.7139e+00, 2.7210e-02],
        [1.4316e+06, 1.4537e+03, 2.9897e+03, 2.1506e+05, 4.2926e+07, 4.1421e+04,
         2.1239e+00, 1.8176e+02, 7.8828e-08, 6.9824e+01],
        [

In [34]:
print('torch.sum(torch.exp(output), dim=1)')
print(torch.sum(torch.exp(output), dim=1))

torch.sum(torch.exp(output), dim=1)
tensor([2.8739e+07, 4.4863e+09, 2.2466e+09, 4.0718e+10, 3.7125e+06, 3.5050e+08,
        4.4619e+07, 2.9485e+04, 4.4128e+05, 1.6551e+08, 1.9651e+10, 9.4408e+09,
        2.0364e+07, 2.2680e+09, 4.4493e+06, 3.8795e+07, 9.8943e+08, 2.3747e+06,
        3.2337e+06, 1.4116e+07, 9.5377e+06, 7.7415e+07, 2.6075e+08, 7.7700e+08,
        7.8233e+05, 5.7305e+06, 2.3356e+04, 3.8895e+09, 2.1864e+10, 4.7267e+09,
        2.0210e+10, 9.5169e+09, 8.5107e+06, 8.8950e+06, 1.3128e+06, 2.8681e+09,
        6.4291e+07, 4.1578e+11, 1.2947e+06, 2.2653e+07, 1.2047e+07, 4.3567e+08,
        1.1474e+07, 1.0153e+08, 2.9208e+09, 8.0328e+07, 2.3163e+09, 4.5189e+06,
        1.8145e+11, 6.5689e+07, 7.7708e+06, 3.3956e+10, 2.0392e+06, 2.3261e+06,
        9.0587e+09, 3.2364e+08, 7.4498e+09, 2.5249e+07, 9.8006e+08, 5.9499e+08,
        3.3324e+07, 5.4457e+07, 9.3202e+08, 1.6464e+09])


In [35]:
print('torch.sum(torch.exp(output), dim=1).view(-1,1)')
print(torch.sum(torch.exp(output), dim=1).view(-1, 1))

torch.sum(torch.exp(output), dim=1).view(-1,1)
tensor([[2.8739e+07],
        [4.4863e+09],
        [2.2466e+09],
        [4.0718e+10],
        [3.7125e+06],
        [3.5050e+08],
        [4.4619e+07],
        [2.9485e+04],
        [4.4128e+05],
        [1.6551e+08],
        [1.9651e+10],
        [9.4408e+09],
        [2.0364e+07],
        [2.2680e+09],
        [4.4493e+06],
        [3.8795e+07],
        [9.8943e+08],
        [2.3747e+06],
        [3.2337e+06],
        [1.4116e+07],
        [9.5377e+06],
        [7.7415e+07],
        [2.6075e+08],
        [7.7700e+08],
        [7.8233e+05],
        [5.7305e+06],
        [2.3356e+04],
        [3.8895e+09],
        [2.1864e+10],
        [4.7267e+09],
        [2.0210e+10],
        [9.5169e+09],
        [8.5107e+06],
        [8.8950e+06],
        [1.3128e+06],
        [2.8681e+09],
        [6.4291e+07],
        [4.1578e+11],
        [1.2947e+06],
        [2.2653e+07],
        [1.2047e+07],
        [4.3567e+08],
        [1.1474e+07],
       

In [36]:
print('torch.exp(output)/(torch.sum(torch.exp(output), dim=1).view(-1,1))')
print(torch.exp(output)/(torch.sum(torch.exp(output), dim=1).view(-1,1)))

torch.exp(output)/(torch.sum(torch.exp(output), dim=1).view(-1,1))
tensor([[3.2683e-05, 1.7930e-06, 1.1801e-06, 2.0272e-05, 2.2518e-01, 9.8964e-04,
         7.7161e-01, 2.1684e-03, 4.5764e-13, 1.2637e-10],
        [3.2464e-06, 4.3775e-11, 2.9016e-11, 2.8771e-10, 1.0000e+00, 1.9205e-09,
         3.1235e-07, 6.9217e-10, 4.2104e-13, 2.9297e-11],
        [9.5769e-06, 1.0583e-11, 2.4518e-04, 1.0961e-07, 9.9652e-01, 3.2274e-03,
         2.4383e-06, 1.1277e-07, 4.6763e-08, 1.8411e-11],
        [5.8666e-07, 2.8368e-13, 2.6038e-10, 1.8836e-08, 9.9989e-01, 1.0575e-04,
         3.7781e-06, 7.6814e-09, 8.0872e-10, 8.8769e-10],
        [1.4149e-03, 4.9704e-05, 1.3005e-05, 1.5229e-04, 6.9754e-05, 3.6263e-02,
         1.6461e-03, 9.6039e-01, 1.4652e-10, 1.9154e-09],
        [3.5533e-05, 9.4577e-12, 1.9739e-04, 4.2587e-07, 9.9807e-01, 1.6024e-03,
         3.1956e-08, 9.2137e-05, 7.7430e-09, 7.7631e-11],
        [3.2086e-02, 3.2581e-05, 6.7006e-05, 4.8200e-03, 9.6206e-01, 9.2834e-04,
         4.7601e-0