<a href="https://colab.research.google.com/github/purvasingh96/pytorch-examples/blob/master/Basics/02.%20Autograd_Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd : Automatic Differentiation
The `autograd` package provides automatic differentiation for all operations on Tensors. 

### Tensor

* `torch.Tensor` is the central class of the package
* Setting `requires_grad` as `True`, tensor will start to track all operations on it.
* Call `.backward()` to compute gradients automatically.
* While training neural network, to prevent tracking of history, use `torch.no_grad()`

In [0]:
import torch

x = torch.ones(2,3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [0]:
# y = 2x
y = x*2
print('operation 1 : ', y)

operation 1 :  tensor([[2., 2., 2.],
        [2., 2., 2.]], grad_fn=<MulBackward0>)


In [0]:
# y = 2x
# z = 32x^2
z = y*y*8
print('operation 2 : ', z)


operation 2 :  tensor([[32., 32., 32.],
        [32., 32., 32.]], grad_fn=<MulBackward0>)


In [0]:
tensor_1 = torch.rand(2,2)
tensor_1 = ((tensor_1*3)/(tensor_1 -1))
print(tensor_1.requires_grad)
tensor_1.requires_grad_(True)
print(tensor_1.requires_grad)
tensor_2 = tensor_1+6
# mean tensor = (32x^2)/6
mean_tensor = z.mean()

print(z.mean())
print(tensor_2.grad_fn)

False
True
tensor(32., grad_fn=<MeanBackward0>)


### Backward() and requires_grad()


In [0]:
mean_tensor.backward()

RuntimeError: ignored

In [0]:
'''
Calculating d(x)/dx
x = 1/6(32*x^2)
d(x)/dx = 1/6(64*x); x= 1; 64/6; 10.6667
'''
x.grad

tensor([[10.6667, 10.6667, 10.6667],
        [10.6667, 10.6667, 10.6667]])

# Autograd
Main idea behind differentiation is to calculate the vector-jacobian product.<br>
<img src="https://github.com/purvasingh96/pytorch-examples/blob/master/Basics/images/jacobian_product.png?raw=1"></img><br><br>
This characteristic of vector-Jacobian product makes it very convenient to feed external gradients into a model that has non-scalar output.<br>


In [3]:
import torch
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float)
x = torch.rand(3, requires_grad=True)
# y has a non scalar value
y = x*3
print(y)

tensor([0.0686, 0.9892, 2.8836], grad_fn=<MulBackward0>)


In case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to backward as argument.

In [5]:
y.backward(v)
print(x.grad)

RuntimeError: ignored

### torch.no_grad() and detach()
To stop autograd from tracking history on Tensors with `.requires_grad=True` either by wrapping the code block in with `torch.no_grad()`.<br>


In [6]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


Use `.detach()` to get a new Tensor with the same content but that does not require gradients:

In [7]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False
